export const SECTION_ADD_REQUEST = 'SECTION.ADD.REQUEST';
export const SECTION_ADDED = 'SECTION.ADD.DONE';
export const ROW_ADD_REQUEST = 'ROW.ADD.REQUEST';
export const ROW_ADDED = 'ROW.ADDED';

export const ROW_REORDER_REQUEST =  'ROW.REORDER.REQUEST';