export const SECTION_ADD_REQUEST = 'SECTION.ADD.REQUEST';
export const SECTION_ADDED = 'SECTION.ADD.DONE';

export const SECTION_REMOVE_REQUEST = 'SECTION.REMOVE.REQUEST';
export const SECTION_REMOVED = 'SECTION.REMOVE.DONE';

export const ROW_ADD_REQUEST = 'ROW.ADD.REQUEST';
export const ROW_ADDED = 'ROW.ADDED';

export const ROW_REMOVE_REQUEST = 'ROW.REMOVE.REQUEST';
export const ROW_REMOVED= 'ROW.REMOVE.DONE';


export const CONTROL_ADD_REQUEST = 'CONTROL.ADD.REQUEST';
export const CONTROL_ADDED = 'CONTROL.ADD.DONE';

export const CONTROL_REMOVE_REQUEST = 'CONTROL.REMOVE.REQUEST';
export const CONTROL_REMOVED = 'CONTROL.REMOVE.DONE';


/// EVENT FOR UI 

export const UI_OPEN_EDIT_CONTROL_DIALOG = 'UI_OPEN_EDIT_CONTROL_DIALOG';


// export const ROW_REORDER_REQUEST =  'ROW.REORDER.REQUEST';